name: Trigger auto deployment for authen

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/authen-AutoDeployTrigger-e641e4cb-14a8-4207-82d5-4a91bc5aee42.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistry012.azurecr.io
          username: ${{ secrets.AUTHEN_REGISTRY_USERNAME }}
          password: ${{ secrets.AUTHEN_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistry012.azurecr.io/authen:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AUTHEN_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n authen -g UnoAuthentificationDemo_group --server containerregistry012.azurecr.io --username  ${{ secrets.AUTHEN_REGISTRY_USERNAME }} --password ${{ secrets.AUTHEN_REGISTRY_PASSWORD }}
            az containerapp update -n authen -g UnoAuthentificationDemo_group --image containerregistry012.azurecr.io/authen:${{ github.sha }}
